# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

pool:
  vmImage: ubuntu-24.04

steps:
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'test222'
    dockerComposeFile: 'welcome-to-docker2025 /docker-compose.yml'
    projectName: 'welcome-to-docker2025'
    action: 'Build services'

- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'test222'
    dockerComposeFile: 'welcome-to-docker2025 /docker-compose.yml'
    projectName: 'welcome-to-docker2025'
    action: 'Push services'
    additionalImageTags: 'Dockerfile'
